export type Role = "admin" | "user";
export type Need = {
  id: string;
  period_id: string | null;
  created_at: string;
  updated_at: string;
  owner_id: string;
  status: string;
  type: string;
  factor: string;
  competency: string;
  gap: string;
  objective: string;
  occupational_group: string;
  area: string;
  department: string;
  position: string;
  participants: number;
  hours: number | null;
  goal: string;
  indicator: string;
  evidence: string;
  priority: string;
  priority_reason: string;
  planned_date: string | null;
  planned_start_date: string | null;
  planned_end_date: string | null;
  quarter: string | null;
  modality: string;
  estimated_cost: number | null;
  provider: string;
  observations: string;
};
export type PlanningPeriod = { id: string; name: string; start_date: string; end_date: string; active: boolean; created_at: string };
export type Catalog = { id: string; kind: string; name: string; active: boolean };
export type Profile = {
  id: string;
  email: string;
  username: string;
  must_change_password: boolean;
  full_name: string | null;
  role: Role;
  active: boolean;
  created_at: string;
  position: string | null;
  occupational_group: string | null;
  area: string | null;
  department: string | null;
  onboarding_completed_at: string | null;
  can_view_entire_area: boolean;
  profile_updated_at: string;
  deleted_at: string | null;
  deleted_by: string | null;
};
export type OrgUnit = {
  id: string;
  group_name: string;
  area_name: string;
  department_name: string;
  active: boolean;
  created_at: string;
};
